[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/sportslot-backend.jar"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"